apiVersion: v1
kind: Secret
metadata:
  name: backend-mongo-secret
type: Opaque
data:
# note: all secrets should be encoded as base64
  api-key: ""
  api-url: ""
  mongo-username: ""
  mongo-password: ""
