apiVersion: apps/v1
kind: Deployment
metadata:
  name: mini-terminal-backend
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: mini-terminal
      component: backend
  template:
    metadata:
      labels:
        app: mini-terminal
        component: backend
    spec:
      containers:
        - name: mini-terminal-backend
          image: motetshurdle6p/mini-terminal-fastapi:2
          ports:
            - containerPort: 8000
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-mongo-secret
                  key: api-key
            - name: API_URL_ROOT
              valueFrom:
                secretKeyRef: 
                  name: backend-mongo-secret
                  key: api-url
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: backend-mongo-secret
                  key: mongo-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef: 
                  name: backend-mongo-secret
                  key: mongo-password
